# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Lint
version:      2.02
version_from: lib/HTML/Lint.pm
installdirs:  site
requires:
    Exporter:                      0
    File::Find:                    0
    HTML::Parser:                  3.20
    HTML::Tagset:                  3.03
    Test::Builder:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
