--- #YAML:1.0
name:                HTML-Lint
version:             2.06
abstract:            check for HTML errors in a string or file
license:             perl
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Exporter:                      0
    File::Find:                    0
    HTML::Parser:                  3.20
    HTML::Tagset:                  3.03
    Test::Builder:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    homepage: http://search.cpan.org/dist/html-lint
    bugtracker: http://code.google.com/p/html-lint/issues/list
    license: http://dev.perl.org/licenses/
    Repository: http://code.google.com/p/html-lint/source
