---
abstract: 'check for HTML errors in a string or file'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Lint
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  File::Find: 0
  HTML::Entities: 0
  HTML::Parser: 3.47
  HTML::Tagset: 3.03
  Test::Builder: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/petdance/html-lint/issues
  homepage: http://search.cpan.org/dist/html-lint
  license: http://www.opensource.org/licenses/artistic-license-2.0.php
  x_Repository: https://github.com/petdance/html-lint
version: 2.11_01
