#!/usr/bin/perl -wT

use strict;

use lib qw( /home/alester/html-lint/lib );

use HTML::Lint;
use HTML::Lint::HTML4;

die "Must specify a file to lint\n" unless @ARGV;

my $lint = new HTML::Lint;
for my $filename ( @ARGV ) {
    $lint->newfile( $filename );

    open( my $fh, $filename ) or $lint->gripe( 'file-cannot-open', filename => $filename, error => $! ), next;
    
    while ( my $line = <$fh> ) {
	$lint->parse( $line );
    }

    close $fh;

    $lint->eof;
} # for files

for my $error ( $lint->errors() ) {
    print $error->as_string(), "\n";
}
